### ISSUE TITLE
[Docs][ReKarel] Agregar una lista de los hotkeys

### ISSUE THREAD

**Issue by kishtarn555** [kishtarn555/ReKarel#32]

**Comment by jamperezmondragon** [comment]
Hola, donde estás desarrollando los docs? en este mismo documento? Si quieres dame un breve resumen de lo que quieres poner y puedo hacer un draft en inglés (y en español si quieres). 

ps: quieres que traduzca el readme a español ?

**Comment by kishtarn555** [comment]
Los docs son en este mismo repo [aquí](https://github.com/kishtarn555/ReKarel/tree/master/webapp/html/docs) y son accesibles a través de la app

![image](https://github.com/user-attachments/assets/cca0d397-30e1-4061-ba66-90c312ce594c)

El nombre de manual de trucos es legacy jaja, así lo llamaban en Karel.js.

**Comment by jamperezmondragon** [comment]
Va, ya ví. La lista de hotkeys que hay que agregar a la documentación son los siguientes?

- Dada una selección de celdas, se puede cambiar el estado de las paredes (si no existe se agrega, si existe se borra) en el borde izquierdo de la selección con `a`, las paredes del borde derecho con `d`, del borde de arriba con `w` y del borde de abajo con `s`.

- Dada una selección de celdas, se puede asignar una cantidad de zumbadores a todas las celdas en la selección. Usando las teclas `qe` se asigna un zumbador a cada celda. Con `1`, `2`, `3`, ... , `9` puedes asignarle esa cantidad de zumbadores a la selección. Con `qc` generas un prompt que te permite seleccionar exactamente cuantos zumbadores deseas asignar a cada celda. Y con `qr` le asignas una cantidad aleatoria de zumbadores a cada celda de la selección.

- `ctrl+k` disminuye el tamaño de la fuente del editor, y `ctrl+l` lo aumenta.


Si sí, dame un momento y los agrego al html

**Comment by jamperezmondragon** [comment]
Ahh me acabo de dar cuenta que `q` le resta un zumbador a cada celda de la selección y que no es necesario escribirlo antes del resto de comandos. También me dí cuenta que `t` asigna infinitos sumbadores a la selección. 

también me dí cuenta que existe este archivo xd

![image](https://github.com/user-attachments/assets/c9c65bb3-505f-411e-b20e-adce2fb848ed)

Supongo que los números que salen ahí en cada definición son código ascii? Creo que puedo deducir qué hace qué mañana temprano con verlo un rato. Puedo hacer un archivo html y agregar esa info al readme mañana también si te parece.

**Comment by jamperezmondragon** [comment]
Otra cosa, no sé si es un bug, pero por lo que entiendo todos los códigos ascii que salen en los hotkeys son letras mayúsculas. Sin embargo solo funcionan cuando  usas letras minúsculas. Además, si usas letras mayúsculas, la acción le es aplicada a la celda inferior izquierda de la selección. Esto aplica para cuando mueves a karel con `P`, cuando restas un zumbador con `Q` cuando agregas infinitos con `T`, cuando haces `6 + shift` u otro número, etc... Ese es el funcionamiento que quieres que tenga `shift`?

**Comment by kishtarn555** [comment]
Hola, a mi me funcionan con minusculas y mayusculas.

El shift aplica la acción en donde tengas el mouse

**Comment by jamperezmondragon** [comment]
Mmmm que interesante, lo volví a probar es cierto lo que dices, cuando hago shift la acción se ejecuta en la casilla sobre la cuál está el mouse. Va, pues mañana temprano si quieres hago un draft de los nuevos documentos te late?

**Comment by jamperezmondragon** [comment]
Hola, aquí abajo te pongo las hotkeys que ví en el archivo y confirmé que funcionan (creo que así como está formateado el markdown es buena idea ponerlo en el html).

Sin embargo, hubo algunos que no pude hacer funcionar. 

- `ctrl-z` para undo y `ctrl-y` para redo.
- `.` para borrar dentro de una selección.
- `%`, `&`, `'`, `(` para mover la selección.

eso es lo que entiendo que hacen estas líneas de código;

![image](https://github.com/user-attachments/assets/0a6283b3-14d0-4b0e-a304-c1a6c08b3a22)
![image](https://github.com/user-attachments/assets/75d63fc8-ca4b-458b-a4f8-bd557ca1cf20)


Tal vez el problema es que para generar el caracter ascii `%` tienes que hacer básicamente `shift+5` en mi teclado, y esa combinación ya tiene una funcionalidad asignada. Sin embargo, en mi teclado hay una tecla dedicada para `'`que no tiene ninguna funcionalidad entonces no entiendo bien qué pasa.

# Hotkeys


- `ctrl-k` disminuye el tamaño de la fuente del editor, y `ctrl+l` lo aumenta.

- `p` mueve la posición de Karel a la celda seleccionada (cuando seleccionas más celdas, se mueve a la principal, resaltada con un punto). 

- `g` mueve la posición de Karel a la celda seleccionada y además gira su dirección en sentido anti horario.

- `r` asigna una cantidad aleatoria de zumbadores a las celdas seleccionadas. Si presionas `alt+r` generas un prompt para elegir el rango de números aleatorios que desees.

- `q` le resta uno a la cantidad de zumbadores en cada una de las celdas seleccionadas.

- `e` le suma uno a la cantidad de zumbadores en cada una de las celdas seleccionadas.

- `0`, `1`, `2`, ..., `9` le asignan esa cantidad de zumbadores a las celdas seleccionadas.

- `t` asigna infinito a la cantidad de zumbadores en cada una de las celdas seleccionadas.

- `c` genera un prompt donde puedes especificar cuántos zumbadores asignarle a cada una de las celdas seleccionadas.

- `w` cambia el estado de las paredes del borde norte de la selección, es decir, si no existe se agrega, si existe se borra.

- `d` cambia el estado de las paredes del borde este de la selección.

- `s` cambia el estado de las paredes del borde sur de la selección.

- `a` cambia el estado de las paredes del borde oeste de la selección.

- `x` cambia el estado de todas las paredes en el borde de la selección.

- `z` resalta las celdas de la selección.

- `backspace` borra todo (zumbadores, paredes y celdas resaltadas) dentro de la selección salvo paredes en los bordes. 

- Adicionalmente, usar cualquiera de estos comandos con `shift` hará que la funcionalidad aplique solamente a la celda sobre la cuál esté el mouse.

**Comment by kishtarn555** [comment]
No es ascii. Es jquery. Son las flechitas para mover la selección 

Borrar es con backspace y suprimir.

Undo y Redi si funciona en mi laptop, pero lo checo al rato

¿Que navegador usas?

**Comment by jamperezmondragon** [comment]
Ohh entiendo, que raro. uso firefox. Bueno, mientras, supongo que este texto está bien? qué te parece ?  lo voy pasando a html?

# Hotkeys


- `ctrl-k` disminuye el tamaño de la fuente del editor, y `ctrl+l` lo aumenta.

- `p` mueve la posición de Karel a la celda seleccionada (cuando seleccionas más celdas, se mueve a la principal, resaltada con un punto). 

- `g` mueve la posición de Karel a la celda seleccionada y además gira su dirección en sentido anti horario.

- `r` asigna una cantidad aleatoria de zumbadores a las celdas seleccionadas. Si presionas `alt+r` generas un prompt para elegir el rango de números aleatorios que desees.

- `q` le resta uno a la cantidad de zumbadores en cada una de las celdas seleccionadas.

- `e` le suma uno a la cantidad de zumbadores en cada una de las celdas seleccionadas.

- `0`, `1`, `2`, ..., `9` le asignan esa cantidad de zumbadores a las celdas seleccionadas.

- `t` asigna infinito a la cantidad de zumbadores en cada una de las celdas seleccionadas.

- `c` genera un prompt donde puedes especificar cuántos zumbadores asignarle a cada una de las celdas seleccionadas.

- `w` cambia el estado de las paredes del borde norte de la selección, es decir, si no existe se agrega, si existe se borra.

- `d` cambia el estado de las paredes del borde este de la selección.

- `s` cambia el estado de las paredes del borde sur de la selección.

- `a` cambia el estado de las paredes del borde oeste de la selección.

- `x` cambia el estado de todas las paredes en el borde de la selección.

- `z` resalta las celdas de la selección.

- `backspace` borra todo (zumbadores, paredes y celdas resaltadas) dentro de la selección salvo paredes en los bordes. 

- 'delete' (o en algunos teclados `suprimir`) borra todo (zumbadores, paredes y celdas reslatadas) dentro de la selección salvo paredes en los bordes.

- Puedes usar las flechas del teclado para mover la selección.

- `ctrl-z` deshace una operación y `ctrl-y` lo revierte.

**Comment by kishtarn555** [comment]
LGTM

**Comment by kishtarn555** [comment]
Bueno, no, 
`z` hace que se evalué una casilla
`v` hace que no se evalué una casilla

Evaluar significa que su valor se guarde en el mundo.out

**Comment by jamperezmondragon** [comment]
Okay, comenzaré a trabajar en el html con esos cambios.

**Comment by kishtarn555** [comment]
@jamperezmondragon , sigues trabajando en este issue?
